server:
  port: 1000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
spring:
  application:
    name: study-provider
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream